name: controllable_gan
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - imageio=2.5.0
  - numpy=1.16.4
  - matplotlib=3.2.1
  - python=3.7.4
  - cudatoolkit=10.0
  - pytorch=1.2.0
  - torchvision=0.4.0
  - tensorboard
  - pip=19.2.2
  - pyyaml=5.3.1
  - tqdm=4.32.0
  - scipy=1.5.0
  - scikit-image=0.16.2
  - pip:
    - tensorboardX
