data:
  name: shapenet_car
  sub_dirs: ['car1_bg0', 'car2_bg0', 'car3_bg0']
generator:
  render_type: point
  bg_cube: False
training:
  out_dir: results/ablation
  param_transforms: none
  weight_3dconsistency: 0.
